import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import worker from '../index';
import {sqliteD1} from './sqlite-d1';
import {digest} from '../lib/account-session';
import type {Env} from '../lib/types';
vi.mock('../lib/chain-identity',()=>({rpcMatchesConfiguredChain:vi.fn(async()=>true)}));
vi.mock('../lib/policy',()=>({getOnChainCollection:vi.fn(async()=>({owner:'0x'+'11'.repeat(20)}))}));
import {getOnChainCollection} from '../lib/policy';
import {rpcMatchesConfiguredChain} from '../lib/chain-identity';
let store:ReturnType<typeof sqliteD1>,env:Env;
const addresses=['11','22','33'].map(x=>'0x'+x.repeat(20)),id='0x'+'aa'.repeat(32),csrf='cc'.repeat(32);
async function call(path:string,method='GET',body?:unknown,who=0){return worker.fetch(new Request('https://vault.example/api/'+path,{method,headers:{Origin:'https://vault.example','Content-Type':'application/json',Cookie:'dv_session='+String(who+1).repeat(64),'x-csrf-token':csrf,'CF-Connecting-IP':String(who)},...(body===undefined?{}:{body:JSON.stringify(body)})}),env);}
async function create(){const r=await call('account/workspaces','POST',{name:'Research'});expect(r.status).toBe(201);return (await r.json() as any).workspace.id as string;}
async function invite(w:string,who=1,role='Editor'){const r=await call(`workspaces/${w}/invitations`,'POST',{address:addresses[who],role});expect(r.status).toBe(201);return (await r.json() as any).invitation.id;}
async function accept(w:string,i:string,who=1){return call(`workspaces/${w}/invitations/${i}/accept`,'POST',{},who);}
beforeEach(async()=>{store=sqliteD1();env={DB:store.db,CHAIN_ID:'10143',CONTRACT_ADDRESS:'0x'+'ab'.repeat(20)} as Env;vi.mocked(getOnChainCollection).mockResolvedValue({owner:addresses[0]} as any);vi.mocked(rpcMatchesConfiguredChain).mockResolvedValue(true);for(let n=0;n<3;n++){await env.DB.prepare('INSERT INTO accounts(account_id,address,chain_id,contract_address,created_at,updated_at) VALUES(?,?,?,?,1,1)').bind('a'+n,addresses[n],10143,env.CONTRACT_ADDRESS).run();await env.DB.prepare('INSERT INTO account_sessions(token_hash,account_id,csrf_token,expires_at,created_at) VALUES(?,?,?,?,1)').bind(await digest(String(n+1).repeat(64)),'a'+n,csrf,Date.now()+1000000).run();}await env.DB.prepare("INSERT INTO collections(collection_id,owner_address,collection_name,content_hash,created_at,status,chain_id,contract_address) VALUES(?,?,?, ?,1,'confirmed',?,?)").bind(id,addresses[0],'Private study',id,10143,env.CONTRACT_ADDRESS).run();});
afterEach(()=>{vi.restoreAllMocks();store.close();});
it('creates private Owner workspace and denies guessing',async()=>{const w=await create();expect(await (await call('account/workspaces')).json()).toMatchObject({workspaces:[{id:w,role:'Owner'}]});expect((await call(`workspaces/${w}`,'GET',undefined,1)).status).toBe(404);expect((await call(`workspaces/${w}`,'PATCH',{name:'Stolen'},1)).status).toBe(404);});
it('binds invites to wallet, expiry, revocation and retry role',async()=>{const w=await create(),i=await invite(w);expect((await accept(w,i,2)).status).toBe(404);expect((await accept(w,i)).status).toBe(200);expect((await call(`workspaces/${w}/members/${addresses[1]}`,'PATCH',{role:'Viewer'})).status).toBe(200);expect((await accept(w,i)).status).toBe(200);expect(await (await call(`workspaces/${w}`,'GET',undefined,1)).json()).toMatchObject({workspace:{role:'Viewer'}});const j=await invite(w,2);await call(`workspaces/${w}/invitations/${j}`,'DELETE',{});expect((await accept(w,j,2)).status).toBe(404);const k=await invite(w,2);await env.DB.prepare('UPDATE workspace_invitations SET expires_at=1 WHERE id=?').bind(k).run();expect((await accept(w,k,2)).status).toBe(404);});
it('shares only metadata and gates Editor, Viewer and live ownership',async()=>{const w=await create();await accept(w,await invite(w));expect((await call(`workspaces/${w}/collections`,'POST',{collectionId:id})).status).toBe(201);expect((await call(`collections/${id}/metadata?workspaceId=${w}`,'PATCH',{description:'Edited'},1)).status).toBe(200);expect((await call(`collections/${id}/metadata`,'PATCH',{description:'No'},1)).status).toBe(403);expect((await call(`workspaces/${w}`,'PATCH',{name:'No'},1)).status).toBe(403);await call(`workspaces/${w}/members/${addresses[1]}`,'PATCH',{role:'Viewer'});expect((await call(`collections/${id}/metadata?workspaceId=${w}`,'PATCH',{description:'No'},1)).status).toBe(403);const feed=await (await call(`workspaces/${w}/collections`,'GET',undefined,1)).json();expect(feed).toMatchObject({collections:[{collectionId:id,description:'Edited'}]});expect(JSON.stringify(feed)).not.toMatch(/content_hash|r2|buyer|answer/);vi.mocked(getOnChainCollection).mockResolvedValue({owner:addresses[2]} as any);expect(await (await call(`workspaces/${w}/collections`,'GET',undefined,1)).json()).toMatchObject({collections:[]});vi.mocked(rpcMatchesConfiguredChain).mockResolvedValue(false);expect((await call(`workspaces/${w}/collections`,'GET',undefined,1)).status).toBe(503);});
it('keeps one Owner under real concurrent SQLite removals',async()=>{const w=await create();await accept(w,await invite(w,1,'Owner'));const r=await Promise.all([call(`workspaces/${w}/leave`,'POST',{},0),call(`workspaces/${w}/leave`,'POST',{},1)]);expect(r.map(x=>x.status).sort()).toEqual([200,409]);expect(store.sqlite.prepare("SELECT * FROM workspace_members WHERE workspace_id=? AND role='Owner'").all(w)).toHaveLength(1);});
it('joins account quota before workspace or chain work',async()=>{const w=await create();for(let n=0;n<19;n++)expect((await call(`workspaces/${w}`,'PATCH',{name:'Name '+n})).status).toBe(200);const r=await call(`workspaces/${w}/collections`,'POST',{collectionId:id});expect(r.status).toBe(429);expect(r.headers.get('Retry-After')).toBe('60');expect(getOnChainCollection).not.toHaveBeenCalled();});
it('workspace keys require issuer Owner and exact grants, with immediate revocation on removal',async()=>{const w=await create();await accept(w,await invite(w,1,'Owner'));await call(`workspaces/${w}/collections`,'POST',{collectionId:id});const body={name:'Team read',scopes:['collections:read'],collectionIds:[id],expiresInDays:1,workspaceId:w};const created=await call('account/api-keys','POST',body,1);expect(created.status).toBe(201);const key=await created.json() as any;const read=()=>worker.fetch(new Request('https://vault.example/api/developer/collections',{headers:{Authorization:'Bearer '+key.secret}}),env);expect((await read()).status).toBe(200);const hidden='0x'+'bb'.repeat(32);await env.DB.prepare("INSERT INTO collections(collection_id,owner_address,collection_name,content_hash,created_at,status,chain_id,contract_address) VALUES(?,?,?, ?,1,'confirmed',?,?)").bind(hidden,addresses[0],'Not shared',hidden,10143,env.CONTRACT_ADDRESS).run();expect(JSON.stringify(await (await read()).json())).not.toContain(hidden);expect((await call('account/api-keys','POST',{...body,collectionIds:[hidden]},1)).status).toBe(403);await call(`workspaces/${w}/members/${addresses[1]}`,'PATCH',{role:'Editor'});expect((await read()).status).toBe(401);expect(await (await call('account/api-keys','GET',undefined,1)).json()).toMatchObject({keys:[]});expect((await call('account/api-keys','POST',body,1)).status).toBe(403);});
it('invalidates grants atomically on grantor demotion and preserves personal keys',async()=>{const w=await create();await accept(w,await invite(w,1,'Owner'));await call(`workspaces/${w}/collections`,'POST',{collectionId:id});const created=await call('account/api-keys','POST',{name:'Personal',scopes:['collections:read'],collectionIds:[id],expiresInDays:1});const key=await created.json() as any;expect((await call(`workspaces/${w}/members/${addresses[0]}`,'PATCH',{role:'Editor'},1)).status).toBe(200);expect(store.sqlite.prepare('SELECT * FROM workspace_grants WHERE workspace_id=?').all(w)).toHaveLength(0);expect(await (await call(`workspaces/${w}/collections`,'GET',undefined,1)).json()).toMatchObject({collections:[]});expect((await worker.fetch(new Request('https://vault.example/api/developer/collections',{headers:{Authorization:'Bearer '+key.secret}}),env)).status).toBe(200);});
it('caps owned workspaces, members and pending invitations atomically',async()=>{for(let n=0;n<5;n++)await create();expect((await call('account/workspaces','POST',{name:'Sixth'})).status).toBe(409);expect(store.sqlite.prepare('SELECT * FROM workspaces').all()).toHaveLength(5);const w=(await (await call('account/workspaces')).json() as any).workspaces[0].id;for(let n=0;n<49;n++)await env.DB.prepare("INSERT INTO workspace_members(workspace_id,address,role,joined_at) VALUES(?,?,'Viewer',1)").bind(w,'0x'+(n+100).toString(16).padStart(40,'0')).run();const i=await invite(w,1);expect((await accept(w,i,1)).status).toBe(409);expect(store.sqlite.prepare('SELECT * FROM workspace_members WHERE workspace_id=?').all(w)).toHaveLength(50);for(let n=0;n<49;n++)await env.DB.prepare("INSERT INTO workspace_invitations(id,workspace_id,address,role,inviter,created_at,expires_at) VALUES(?,?,?,'Viewer',?,1,?)").bind((n+100).toString(16).padStart(64,'0'),w,'0x'+(n+200).toString(16).padStart(40,'0'),addresses[0],Date.now()+1000000).run();expect((await call(`workspaces/${w}/invitations`,'POST',{address:addresses[2],role:'Viewer'})).status).toBe(409);expect((await call(`workspaces/${w}/members?limit=51`)).status).toBe(400);const page=await (await call(`workspaces/${w}/members?limit=20`)).json() as any;expect(page.members).toHaveLength(20);expect((await (await call(`workspaces/${w}/members?limit=20&cursor=${page.nextCursor}`)).json() as any).members).toHaveLength(20);},30000);
it('rejects cross deployment and CSRF and never delegates payment or private sources',async()=>{const w=await create();const request=new Request(`https://vault.example/api/workspaces/${w}`,{method:'PATCH',headers:{Origin:'https://vault.example','Content-Type':'application/json',Cookie:'dv_session='+'1'.repeat(64)},body:JSON.stringify({name:'No CSRF'})});expect((await worker.fetch(request,env)).status).toBe(403);expect((await call(`workspaces/${w}`,'PATCH',{active:false})).status).toBe(400);expect((await call(`workspaces/${w}/sources`)).status).toBe(404);expect((await call(`workspaces/${w}/answers`)).status).toBe(404);expect((await call(`workspaces/${w}/price`,'POST',{price:1})).status).toBe(404);env.CONTRACT_ADDRESS='0x'+'cd'.repeat(20);expect((await call(`workspaces/${w}`)).status).toBe(401);expect((await call('account/invitations')).status).toBe(401);});
it('denies an Editor removed while chain verification is in flight before metadata write',async()=>{const w=await create();await accept(w,await invite(w));await call(`workspaces/${w}/collections`,'POST',{collectionId:id});let release!:(value:any)=>void;vi.mocked(getOnChainCollection).mockImplementationOnce(()=>new Promise(resolve=>{release=resolve;}));const pending=call(`collections/${id}/metadata?workspaceId=${w}`,'PATCH',{description:'Forbidden late update'},1);while(!release)await new Promise(resolve=>setTimeout(resolve,1));expect((await call(`workspaces/${w}/members/${addresses[1]}`,'DELETE',{})).status).toBe(200);release({owner:addresses[0]});expect((await pending).status).toBe(403);expect(store.sqlite.prepare('SELECT * FROM collection_metadata').all()).toHaveLength(0);});
it('does not return a grant demoted while feed ownership RPC is pending',async()=>{const w=await create();await accept(w,await invite(w,1,'Owner'));await call(`workspaces/${w}/collections`,'POST',{collectionId:id});let release!:(value:any)=>void;vi.mocked(getOnChainCollection).mockImplementationOnce(()=>new Promise(resolve=>{release=resolve;}));const pending=call(`workspaces/${w}/collections`,'GET',undefined,1);while(!release)await new Promise(resolve=>setTimeout(resolve,1));expect((await call(`workspaces/${w}/members/${addresses[0]}`,'PATCH',{role:'Editor'},1)).status).toBe(200);release({owner:addresses[0]});expect(await (await pending).json()).toMatchObject({collections:[]});});
it('rechecks final metadata write authority after successful grant validation',async()=>{const w=await create();await accept(w,await invite(w));await call(`workspaces/${w}/collections`,'POST',{collectionId:id});let release!:(value:any)=>void;vi.mocked(getOnChainCollection).mockResolvedValueOnce({owner:addresses[0]} as any).mockImplementationOnce(()=>new Promise(resolve=>{release=resolve;}));const pending=call(`collections/${id}/metadata?workspaceId=${w}`,'PATCH',{description:'Forbidden final update'},1);while(!release)await new Promise(resolve=>setTimeout(resolve,1));expect((await call(`workspaces/${w}/members/${addresses[1]}`,'DELETE',{})).status).toBe(200);release({owner:addresses[0]});expect((await pending).status).toBe(403);expect(store.sqlite.prepare('SELECT * FROM collection_metadata').all()).toHaveLength(0);});
it('concurrent acceptance retries preserve one membership and one accepted audit',async()=>{const w=await create(),i=await invite(w);const results=await Promise.all([accept(w,i),accept(w,i)]);expect(results.map(r=>r.status)).toEqual([200,200]);expect(store.sqlite.prepare('SELECT * FROM workspace_members WHERE workspace_id=? AND address=?').all(w,addresses[1])).toHaveLength(1);expect(store.sqlite.prepare("SELECT * FROM workspace_audit WHERE workspace_id=? AND action='accepted'").all(w)).toHaveLength(1);});
