import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createServer} from 'vite';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
test('workspace reads and mutations discard delayed private results after wallet change',async()=>{
 const cacheDir=mkdtempSync(join(tmpdir(),'dv-team-test-'));const vite=await createServer({cacheDir,configFile:false,optimizeDeps:{noDiscovery:true},server:{middlewareMode:true},appType:'custom',logLevel:'silent'});
 try {const {AccountClient}=await vite.ssrLoadModule('/src/production/account-client.ts');const address='0x'+'11'.repeat(20),csrf='ab'.repeat(32),session={account:{address,displayName:'',locale:'en-GB',notificationPreferences:{inApp:true,email:false},createdAt:1,updatedAt:1},csrfToken:csrf,expiresAt:new Date(Date.now()+86400000).toISOString()};
 for(const mutation of [false,true]){let release,record;const client=new AccountClient(31337,'0x'+'ab'.repeat(20),async(path,init={})=>{if(path==='/api/account')return new Response(JSON.stringify(session));if(path.startsWith('/api/workspaces/')){record=init;return new Promise(resolve=>{release=()=>resolve(new Response(JSON.stringify({workspace:{name:'Private'}})));});}return new Response(null,{status:204});});await client.setWallet({address},true);const pending=client.workspaceRequest('aa'.repeat(32),mutation?'PATCH':'GET',mutation?{name:'New'}:undefined);await new Promise(resolve=>setImmediate(resolve));if(mutation)assert.equal(record.headers['x-csrf-token'],csrf);await client.setWallet(null,false);release();assert.equal(await pending,null);}
 }finally{await vite.close();rmSync(cacheDir,{recursive:true,force:true});}
});
import React from 'react';
import {act,create} from 'react-test-renderer';
import {createRequire} from 'node:module';
const {MemoryRouter}=createRequire(import.meta.url)('../node_modules/react-router/dist/development/index.js');
test('team UI gates role controls and immediately hides previous wallet private results',async()=>{
 const cacheDir=mkdtempSync(join(tmpdir(),'dv-team-ui-'));
 const fixture={session:{account:{address:'0x'+'11'.repeat(20)},csrfToken:'aa'.repeat(32)},loading:false,error:''};
 const workspaceId='ab'.repeat(32);let userRole='Editor';
 const client={state:{error:''},teams:async()=>({workspaces:[{id:workspaceId,name:'Private team',role:userRole,createdAt:1}],invitations:[]}),workspaceRequest:async(path)=>path===workspaceId?{workspace:{id:workspaceId,name:'Private team',role:userRole,createdAt:1}}:path.includes('/members')?{members:[{address:fixture.session.account.address,role:userRole,joinedAt:1}]}:path.includes('/collections')?{collections:[{collectionId:'0x'+'aa'.repeat(32),name:'Shared private study',description:'Private metadata',category:'Research',visibility:'unlisted'}],nextCursor:null}:{invitations:[]}};
 globalThis.__teamFixture={client,state:fixture};
 const vite=await createServer({cacheDir,configFile:false,envDir:cacheDir,define:{'import.meta.env.VITE_CHAIN_ID':'31337','import.meta.env.VITE_CONTRACT_ADDRESS':JSON.stringify('0x'+'ab'.repeat(20))},plugins:[{name:'team-fixture',enforce:'pre',transform(code,id){if(id.replaceAll('\\','/').endsWith('/production/account.tsx'))return 'export const useAccount=()=>globalThis.__teamFixture;';if(id.replaceAll('\\','/').endsWith('/production/data.tsx'))return 'export const useWorkspace=()=>({collections:{data:null},loading:false,load:async()=>{}});';}}],optimizeDeps:{noDiscovery:true},server:{middlewareMode:true},appType:'custom',logLevel:'silent'});
 let renderer;
 try{const {default:TeamSettings}=await vite.ssrLoadModule('/src/production/TeamSettings.tsx');const element=()=>React.createElement(MemoryRouter,null,React.createElement(TeamSettings));await act(async()=>{renderer=create(element());});const button=label=>renderer.root.findAllByType('button').find(b=>b.children.join('').includes(label));await act(async()=>{button('Private team').props.onClick();});let text=JSON.stringify(renderer.toJSON());assert.match(text,/Edit shared metadata/);assert.doesNotMatch(text,/Create wallet invitation|Save workspace name|Remove member/);assert.match(text,/Shared private study/);
 userRole='Viewer';await act(async()=>{button('Private team').props.onClick();});text=JSON.stringify(renderer.toJSON());assert.doesNotMatch(text,/Edit shared metadata|Create wallet invitation/);
 fixture.session=null;await act(async()=>{renderer.update(element());});text=JSON.stringify(renderer.toJSON());assert.doesNotMatch(text,/Private team|Shared private study|Private metadata/);assert.match(text,/Sign in to manage wallet invitations/);
 }finally{if(renderer)await act(async()=>renderer.unmount());delete globalThis.__teamFixture;await vite.close();rmSync(cacheDir,{recursive:true,force:true});}
});
test('team hydration can overlap existing account status hydration without dropping a read',async()=>{
 const cacheDir=mkdtempSync(join(tmpdir(),'dv-team-read-'));const vite=await createServer({cacheDir,configFile:false,optimizeDeps:{noDiscovery:true},server:{middlewareMode:true},appType:'custom',logLevel:'silent'});
 try{const {AccountClient}=await vite.ssrLoadModule('/src/production/account-client.ts');const address='0x'+'11'.repeat(20),session={account:{address,displayName:'',locale:'en-GB',notificationPreferences:{inApp:true,email:false},createdAt:1,updatedAt:1},csrfToken:'ab'.repeat(32),expiresAt:new Date(Date.now()+86400000).toISOString()};let release;const client=new AccountClient(31337,'0x'+'ab'.repeat(20),async(path)=>{if(path==='/api/account')return new Response(JSON.stringify(session));if(path==='/api/account/email')return new Promise(resolve=>{release=()=>resolve(new Response(JSON.stringify({providerConfigured:false})));});return new Response(JSON.stringify(path.includes('invitations')?{invitations:[]}:{workspaces:[]}));});await client.setWallet({address},true);const email=client.emailStatus();await new Promise(resolve=>setImmediate(resolve));const teams=await client.teams();release();await email;assert.deepEqual(teams,{workspaces:[],invitations:[]});
 }finally{await vite.close();rmSync(cacheDir,{recursive:true,force:true});}
});
test('AccountSettings hydrates email and teams together and discards both on wallet sign-out',async()=>{
 const cacheDir=mkdtempSync(join(tmpdir(),'dv-account-team-'));const address='0x'+'11'.repeat(20),session={account:{address,displayName:'',locale:'en-GB',notificationPreferences:{inApp:true,email:false},createdAt:1,updatedAt:1},csrfToken:'ab'.repeat(32),expiresAt:new Date(Date.now()+86400000).toISOString()};let releaseEmail,releaseTeams;
 const vite=await createServer({cacheDir,configFile:false,envDir:cacheDir,define:{'import.meta.env.VITE_CHAIN_ID':'31337','import.meta.env.VITE_CONTRACT_ADDRESS':JSON.stringify('0x'+'ab'.repeat(20))},plugins:[{name:'account-team-fixture',enforce:'pre',transform(code,id){const p=id.replaceAll('\\','/');if(p.endsWith('/production/account.tsx'))return 'export const useAccount=()=>({client:globalThis.__accountTeamClient,state:globalThis.__accountTeamClient.state});';if(p.endsWith('/production/data.tsx'))return 'export const useWorkspace=()=>({collections:{data:null},loading:false,load:async()=>{}});';if(p.endsWith('/lib/wallet.tsx'))return 'export const useWallet=()=>({primaryWallet:null,correctNetwork:true});';}}],optimizeDeps:{noDiscovery:true},server:{middlewareMode:true},appType:'custom',logLevel:'silent'});
 let renderer;
 try{const {AccountClient}=await vite.ssrLoadModule('/src/production/account-client.ts');const client=new AccountClient(31337,'0x'+'ab'.repeat(20),async(path)=>{if(path==='/api/account')return new Response(JSON.stringify(session));if(path==='/api/account/email')return new Promise(resolve=>{releaseEmail=()=>resolve(new Response(JSON.stringify({verifiedEmail:'private@example.com',providerConfigured:true,resendAfter:0})));});if(path==='/api/account/workspaces')return new Promise(resolve=>{releaseTeams=()=>resolve(new Response(JSON.stringify({workspaces:[{id:'ab'.repeat(32),name:'Private account workspace',role:'Owner',createdAt:1}]})));});if(path==='/api/account/invitations')return new Response(JSON.stringify({invitations:[]}));return new Response(null,{status:204});});await client.setWallet({address},true);globalThis.__accountTeamClient=client;const {default:AccountSettings}=await vite.ssrLoadModule('/src/production/AccountSettings.tsx');const element=()=>React.createElement(MemoryRouter,null,React.createElement(AccountSettings));await act(async()=>{renderer=create(element());});assert.equal(typeof releaseEmail,'function','Email request must start while team request waits');assert.equal(typeof releaseTeams,'function','Team request must start during account hydration');await act(async()=>{await client.setWallet(null,false);renderer.update(element());});releaseEmail();releaseTeams();await act(async()=>{await new Promise(resolve=>setImmediate(resolve));});const text=JSON.stringify(renderer.toJSON());assert.doesNotMatch(text,/private@example.com|Private account workspace/);assert.match(text,/Sign in to account/);
 }finally{if(renderer)await act(async()=>renderer.unmount());delete globalThis.__accountTeamClient;await vite.close();rmSync(cacheDir,{recursive:true,force:true});}
});
test('workspace domain failures explain Owner responsibilities and role denial without claiming an outage',async()=>{
 const cacheDir=mkdtempSync(join(tmpdir(),'dv-team-errors-'));const vite=await createServer({cacheDir,configFile:false,optimizeDeps:{noDiscovery:true},server:{middlewareMode:true},appType:'custom',logLevel:'silent'});
 try{const {AccountClient}=await vite.ssrLoadModule('/src/production/account-client.ts');const address='0x'+'11'.repeat(20),session={account:{address,displayName:'',locale:'en-GB',notificationPreferences:{inApp:true,email:false},createdAt:1,updatedAt:1},csrfToken:'ab'.repeat(32),expiresAt:new Date(Date.now()+86400000).toISOString()};let status=409,error='Keep at least one Owner; maximum 5 owned workspaces per wallet';const client=new AccountClient(31337,'0x'+'ab'.repeat(20),async(path)=>new Response(JSON.stringify(path==='/api/account'?session:{error}),{status:path==='/api/account'?200:status}));await client.setWallet({address},true);assert.equal(await client.workspaceRequest('ab'.repeat(32)+'/leave','POST',{}),null);assert.match(client.state.error,/appoint another Owner/i);assert.doesNotMatch(client.state.error,/unavailable|sign in again/i);assert.equal(client.state.session.account.address,address);status=403;error='Owner required';assert.equal(await client.workspaceRequest('ab'.repeat(32),'PATCH',{name:'No'}),null);assert.match(client.state.error,/current workspace Owner/i);assert.doesNotMatch(client.state.error,/sign in again/i);status=409;error='Maximum 5 owned workspaces';await client.createWorkspace('Sixth');assert.match(client.state.error,/5 owned workspaces/);status=409;error='Pending invitation exists or maximum 50 pending invitations';await client.workspaceRequest('ab'.repeat(32)+'/invitations','POST',{});assert.match(client.state.error,/pending invitation.*50/i);status=503;error='private RPC credential SECRET';await client.workspaceRequest('ab'.repeat(32)+'/collections');assert.match(client.state.error,/chain verification/i);assert.doesNotMatch(client.state.error,/SECRET|credential/);status=400;await client.workspaceRequest('bad','POST',{});assert.match(client.state.error,/check/i);assert.doesNotMatch(client.state.error,/SECRET/);status=404;error='Invitation expired or revoked';await client.workspaceRequest('ab'.repeat(32)+'/invitations/x/accept','POST',{});assert.match(client.state.error,/expired or was revoked.*new invitation/i);
 }finally{await vite.close();rmSync(cacheDir,{recursive:true,force:true});}
});
test('AccountSettings leave conflict and Owner denial show actionable domain alerts',async()=>{
 const cacheDir=mkdtempSync(join(tmpdir(),'dv-team-alerts-')),workspaceId='ab'.repeat(32),address='0x'+'11'.repeat(20),session={account:{address,displayName:'',locale:'en-GB',notificationPreferences:{inApp:true,email:false},createdAt:1,updatedAt:1},csrfToken:'ab'.repeat(32),expiresAt:new Date(Date.now()+86400000).toISOString()};
 const vite=await createServer({cacheDir,configFile:false,envDir:cacheDir,define:{'import.meta.env.VITE_CHAIN_ID':'31337','import.meta.env.VITE_CONTRACT_ADDRESS':JSON.stringify('0x'+'ab'.repeat(20))},plugins:[{name:'team-alert-fixture',enforce:'pre',transform(code,id){const p=id.replaceAll('\\','/');if(p.endsWith('/production/account.tsx'))return "import {useState,useEffect} from 'react'; export const useAccount=()=>{const client=globalThis.__teamAlertClient;const [state,setState]=useState(client.state);useEffect(()=>client.subscribe(setState),[client]);return {client,state};};";if(p.endsWith('/production/data.tsx'))return 'export const useWorkspace=()=>({collections:{data:null},loading:false,load:async()=>{}});';if(p.endsWith('/lib/wallet.tsx'))return 'export const useWallet=()=>({primaryWallet:null,correctNetwork:true});';}}],optimizeDeps:{noDiscovery:true},server:{middlewareMode:true},appType:'custom',logLevel:'silent'});
 let renderer;
 try{const {AccountClient}=await vite.ssrLoadModule('/src/production/account-client.ts');const team={id:workspaceId,name:'Local test workspace',role:'Owner',createdAt:1};const client=new AccountClient(31337,'0x'+'ab'.repeat(20),async(path,init={})=>{let value,status=200;if(path==='/api/account')value=session;else if(path==='/api/account/email')value={providerConfigured:false,resendAfter:0};else if(path==='/api/account/workspaces')value={workspaces:[team]};else if(path.endsWith('/leave')){value={error:'Keep at least one Owner; maximum 5 owned workspaces per wallet'};status=409;}else if(init.method==='PATCH'){value={error:'Owner required'};status=403;}else if(path==='/api/workspaces/'+workspaceId)value={workspace:team};else if(path.includes('/members'))value={members:[{address,role:'Owner',joinedAt:1}]};else if(path.includes('/collections'))value={collections:[],nextCursor:null};else value={invitations:[]};return new Response(JSON.stringify(value),{status});});await client.setWallet({address},true);globalThis.__teamAlertClient=client;const {default:AccountSettings}=await vite.ssrLoadModule('/src/production/AccountSettings.tsx');await act(async()=>{renderer=create(React.createElement(MemoryRouter,null,React.createElement(AccountSettings)));});const button=label=>renderer.root.findAllByType('button').find(b=>b.children.join('').includes(label));await act(async()=>button('Local test workspace').props.onClick());await act(async()=>button('Leave workspace').props.onClick());await act(async()=>renderer.root.findAllByType('button').find(b=>b.children.join('')==='Confirm').props.onClick());let text=JSON.stringify(renderer.toJSON());assert.match(text,/Appoint another Owner before leaving/);assert.doesNotMatch(text,/Account service unavailable|Sign in again/);assert.equal(client.state.session.account.address,address);const form=renderer.root.findAllByType('form').find(f=>f.findAllByType('input').some(i=>i.props.value==='Local test workspace'));await act(async()=>form.props.onSubmit({preventDefault(){}}));text=JSON.stringify(renderer.toJSON());assert.match(text,/current workspace Owner must perform this action/);assert.doesNotMatch(text,/Account service unavailable|Sign in again/);
 }finally{if(renderer)await act(async()=>renderer.unmount());delete globalThis.__teamAlertClient;await vite.close();rmSync(cacheDir,{recursive:true,force:true});}
});
