// Generated by Wrangler by running `wrangler types src/email-bindings.generated.d.ts --config wrangler.email.example.toml --env-interface WorkerEmailBindings --strict-vars false`

interface WorkerEmailBindings {
	EMAIL_FROM: string;
	PUBLIC_ORIGIN: string;
	CONTRACT_ADDRESS: string;
	MONAD_RPC_URL: string;
	CHAIN_ID: string;
	SETTLEMENT_PRIVATE_KEY: string;
	MODEL_PROVIDER: string;
	MODEL_API_KEY: string;
	MODEL_API_BASE: string;
	MODEL_NAME: string;
	COLLECTION_STORE: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
}
