import { useState } from 'react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip } from 'recharts';
import { defaultDateWindow, type DateWindow } from './analytics-client';
import type { Analytics } from './api';
import { useWorkspace } from './data';
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);}
export function AnalyticsControls({owner=false}:{owner?:boolean}) {
 const workspace=useWorkspace();const [message,setMessage]=useState(''),[exporting,setExporting]=useState(false);
 const tomorrow=defaultDateWindow().end;
 const change=(part:keyof DateWindow,value:string)=>{workspace.setWindow({...workspace.window,[part]:value});setMessage('');};
 return <section className="dv-card dv-panel"><div className="dv-analytics-controls"><label>Start date (UTC)<input className="dv-input" aria-label="Start date UTC" type="date" value={workspace.window.start} max={tomorrow} onChange={e=>change('start',e.target.value)}/></label><label>End date (UTC, exclusive)<input className="dv-input" aria-label="End date UTC exclusive" type="date" value={workspace.window.end} max={tomorrow} onChange={e=>change('end',e.target.value)}/></label><button className="dv-button secondary" onClick={()=>workspace.setWindow(defaultDateWindow())}>Last 30 days</button>{owner&&<button className="dv-button secondary" disabled={workspace.loading||exporting||workspace.analytics.status!=='ready'} onClick={async()=>{setExporting(true);setMessage('');try{const blob=await workspace.exportAnalytics();if(blob)download(blob,'datavault-owner-analytics.csv');}catch(cause){setMessage((cause as Error).message);}finally{setExporting(false);}}}>{exporting?'Signing export...':'Export owner CSV'}</button>}</div><p>Select 1 to 90 UTC days. The end date is excluded. Owner reads and exports require a wallet signature for this window.</p>{message&&<p role="alert">{message}</p>}</section>;
}
export function DailyCharts({data}:{data:Analytics}){
 return <section className="dv-card dv-panel"><h2>Daily recorded activity</h2><p>{data.windowStart.slice(0,10)} to {data.windowEnd.slice(0,10)} UTC (exclusive end). Failures and refunds are grouped by request creation date, settlements by settlement date.</p><div style={{height:260,width:'100%',minWidth:0}}><ResponsiveContainer width="100%" height="100%"><LineChart data={data.daily} margin={{left:-24,right:8}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis allowDecimals={false}/><Tooltip/><Line dataKey="settledQueries" name="Settled" stroke="#136a4a"/><Line dataKey="failedQueries" name="Failed" stroke="#b43c39"/><Line dataKey="refundedQueries" name="Refunded" stroke="#82602b"/></LineChart></ResponsiveContainer></div><details><summary>Exact daily revenue (wei)</summary><div className="dv-table-scroll"><table className="dv-table"><thead><tr><th>UTC date</th><th>Recorded wei</th><th>Amount coverage</th></tr></thead><tbody>{data.daily.map(day=><tr key={day.date}><td>{day.date}</td><td>{day.recordedRevenueWei}</td><td>{day.knownAmounts}/{day.settledQueries}</td></tr>)}</tbody></table></div></details><p>Revenue is exact for recorded amounts. Missing amounts prevent a complete earnings ranking. Aggregation supports at most 10,000 settlement, failed and refunded records per window.</p></section>;
}
