import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router';
import { useAccount } from './account';
import { useWorkspace } from './data';
import type { ApiKey, KeyUsage, TeamWorkspace, TeamCollection } from './account-client';

export function ApiKeys(){
 const {client,state}=useAccount(),workspace=useWorkspace();
 const identity=state.session?state.session.account.address+':'+state.session.csrfToken:'';
 const current=useRef(identity);current.current=identity;
 const mounted=useRef(true);
 const [loadedFor,setLoadedFor]=useState(''),[keys,setKeys]=useState<ApiKey[]>([]),[usage,setUsage]=useState<KeyUsage|null>(null),[secret,setSecret]=useState<{identity:string;value:string}|null>(null);
 const [name,setName]=useState(''),[ids,setIds]=useState<string[]>([]),[days,setDays]=useState(30),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copyStatus,setCopyStatus]=useState(''),[confirm,setConfirm]=useState<string|null>(null);
 const [teams,setTeams]=useState<TeamWorkspace[]>([]),[teamId,setTeamId]=useState(''),[shared,setShared]=useState<TeamCollection[]>([]);
 const currentTeam=useRef(teamId);currentTeam.current=teamId;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function refresh(captured=identity){
 const list=await client.apiKeys();const counters=await client.apiKeyUsage();const memberships=await client.teams();
 if(mounted.current&&current.current===captured){if(list){setKeys(list.keys);setLoadedFor(captured);}if(counters)setUsage(counters);if(memberships)setTeams(memberships.workspaces.filter(w=>w.role==='Owner'));}
 }
 useEffect(()=>{setSecret(null);setKeys([]);setUsage(null);setLoadedFor('');setIds([]);setConfirm(null);setError('');setCopyStatus('');setBusy(false);setTeams([]);setTeamId('');setShared([]);if(identity)void refresh(identity);},[identity]);
 async function chooseTeam(id:string){const captured=identity;currentTeam.current=id;setTeamId(id);setShared([]);setIds([]);setSecret(null);if(!id)return;setBusy(true);const result=await client.workspaceRequest<{collections:TeamCollection[]}>(id+'/collections?limit=50');if(mounted.current&&current.current===captured&&currentTeam.current===id){if(result)setShared(result.collections);else setError(client.state.error||'Workspace sharing unavailable.');setBusy(false);}}
 const visible=loadedFor===identity&&identity?keys:[],reveal=secret?.identity===identity&&identity?secret.value:null;
 async function create(){const captured=identity;setBusy(true);setError('');setSecret(null);setCopyStatus('');try{
 const result=await client.createApiKey({name,collectionIds:ids,expiresInDays:days,scopes:['collections:read'],...(teamId?{workspaceId:teamId}:{})});
 if(!mounted.current||current.current!==captured)return;
 if(result){setSecret({identity:captured,value:result.secret});setName('');setIds([]);await refresh(captured);}else setError(client.state.error||'Key creation did not complete. Sign in and retry.');
 }finally{if(mounted.current&&current.current===captured)setBusy(false);}}
 async function revoke(id:string){const captured=identity;setBusy(true);setError('');const result=await client.revokeApiKey(id);if(mounted.current&&current.current===captured){if(result){setConfirm(null);setSecret(null);await refresh(captured);}else setError(client.state.error||'Revocation failed. Retry.');setBusy(false);}}
 const collections=teamId?shared:workspace.collections.data?.collections??[];
 return <><header className="dv-page-heading"><div><h1>Developer API keys</h1><p>Read selected collection metadata with scoped keys. Paid queries keep their wallet authorization.</p></div></header>
 <section className="dv-card dv-panel"><h2>Account authorization</h2><p>Sign in with your wallet to create and revoke keys. Keys remain valid after account sign-out until revoked or expired.</p>{state.session?<><p>Signed in to your wallet account.</p><button className="dv-button secondary" disabled={state.loading||busy} onClick={()=>{setSecret(null);void client.signOut();}}>Sign out</button></>:<button className="dv-button" disabled={state.loading} onClick={()=>void client.signIn()}>{state.loading?'Signing in…':'Sign in with wallet'}</button>}{(error||state.error)&&<p role="alert">{error||state.error}</p>}</section>
 {identity&&<><div className="dv-two-columns"><section className="dv-card dv-panel"><h2>Create a key</h2><p>Maximum 5 active keys. Personal keys use wallet-owned collections. Workspace keys require your current Owner membership and valid explicit grants.</p><button className="dv-button secondary" disabled={workspace.loading||busy} onClick={()=>void workspace.load('collections')}>{workspace.loading?'Loading collections…':'Load owned collections'}</button>{workspace.collections.error&&<p role="alert">{workspace.collections.error}</p>}
 <form onSubmit={event=>{event.preventDefault();void create();}} className="dv-collection-edit-form dv-api-key-form"><label>Key access<select className="dv-input" value={teamId} disabled={busy||state.loading} onChange={event=>void chooseTeam(event.target.value)}><option value="">Personal wallet collections</option>{teams.map(team=><option key={team.id} value={team.id}>{team.name} (workspace Owner)</option>)}</select></label><p>Workspace key access stops when its issuer loses Owner membership or a selected grant becomes invalid.</p><label>Name<input className="dv-input" required maxLength={80} value={name} onChange={event=>setName(event.target.value)} disabled={busy}/></label><label>Expires in days<input className="dv-input" type="number" min={1} max={90} value={days} onChange={event=>setDays(Number(event.target.value))} disabled={busy}/></label><fieldset><legend>Allowed collections (1 to 24)</legend>{collections.length?collections.map(collection=><label key={collection.collectionId} className="dv-api-key-choice"><input type="checkbox" checked={ids.includes(collection.collectionId)} disabled={busy||(!ids.includes(collection.collectionId)&&ids.length>=24)} onChange={event=>setIds(old=>event.target.checked?[...old,collection.collectionId]:old.filter(id=>id!==collection.collectionId))}/>{collection.name}</label>):<p>Load your owned collections to select access.</p>}</fieldset><p>Scope: <code>collections:read</code></p><button className="dv-button" disabled={busy||state.loading||ids.length===0||visible.filter(key=>key.status==='active').length>=5}>{busy?'Creating…':'Create key'}</button></form>
 {reveal&&<div className="dv-api-key-reveal"><h3>Save this secret now</h3><p>This secret is shown once. Anyone holding it can read the selected metadata. Store it securely, never put it in URLs or share it. Revoke it if exposed.</p><code>{reveal}</code><div className="dv-detail-actions"><button type="button" className="dv-button secondary" onClick={async()=>{try{await navigator.clipboard.writeText(reveal);if(current.current===identity)setCopyStatus('Copied. Store it securely.');}catch{if(current.current===identity)setCopyStatus('Copy failed. Select the secret and copy it manually.');}}}>Copy secret</button><button type="button" className="dv-button secondary" onClick={()=>setSecret(null)}>Dismiss secret</button></div>{copyStatus&&<p role="status">{copyStatus}</p>}</div>}
 </section><section className="dv-card dv-panel"><h2>Your keys</h2><button className="dv-button secondary" disabled={busy||state.loading} onClick={()=>void refresh()}>Refresh keys and usage</button>{visible.length===0?<p>No keys loaded.</p>:visible.map(key=><article className="dv-api-key-item" key={key.id}><h3>{key.name}</h3><p><code>{key.displayPrefix}…</code> · {key.status}</p><p>{key.scopes.join(', ')}</p><p>Collections: {key.collections?.map(collection=>collection.name).join(', ')||key.collectionIds.join(', ')}</p><p>Expires {new Date(key.expiresAt).toLocaleString()}</p>{key.status==='active'&&(confirm===key.id?<div><p>Revoke permanently? This old key cannot be restored. You can create a new key.</p><div className="dv-detail-actions"><button className="dv-button" disabled={busy} onClick={()=>void revoke(key.id)}>Confirm revoke</button><button className="dv-button secondary" disabled={busy} onClick={()=>setConfirm(null)}>Cancel</button></div></div>:<button className="dv-button secondary" disabled={busy} onClick={()=>setConfirm(key.id)}>Revoke</button>)}</article>)}</section></div>
 <section className="dv-card dv-panel"><h2>Recorded usage</h2>{usage&&loadedFor===identity?<><p>As of {new Date(usage.asOf).toLocaleString()}. Retained for {usage.retentionDays} days. Showing up to {usage.limits.daily} daily and {usage.limits.minute} minute records.</p>{usage.daily.length?usage.daily.map(row=><p key={row.keyId+':'+row.timestamp}>{new Date(row.timestamp).toISOString().slice(0,10)} UTC · {visible.find(key=>key.id===row.keyId)?.name??'Key'}: {row.accepted} successful, {row.rejected} quota rejected, {row.ownershipDenied} ownership denied, {row.chainUnavailable} chain unavailable.</p>):<p>No recorded calls.</p>}{usage.minute.map(row=><p key={row.keyId+':'+row.timestamp}>{new Date(row.timestamp).toISOString()} · {visible.find(key=>key.id===row.keyId)?.name??'Key'}: {row.claimed} quota claims, {row.accepted} successful, {row.rejected} quota rejected.</p>)}</>:<p>Usage has not loaded.</p>}</section></>}
 <section className="dv-card dv-panel"><h2>Integration boundaries</h2><p>Send one Authorization bearer header to GET /api/developer/collections. Keys grant metadata access only. They cannot authorize payments, query execution, answer recovery, admin actions or account sessions.</p><Link to="/collections" className="dv-button secondary">Manage collections</Link> <a href="https://github.com/ShieldTech-Ltd/datavault/blob/master/docs/api-contract.md" target="_blank" rel="noreferrer">Read the API contract</a></section></>;
}
