import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router';
import {useAccount} from './account';
import type {GithubImportJob,GithubConnectionStatus} from './account-client';
export default function GithubImport({onReviewed,onInvalidated}:{onReviewed:(name:string,text:string)=>void;onInvalidated:()=>void}){
 const {client,state}=useAccount();const address=state.session?.account.address;
 const [repository,setRepository]=useState(''),[ref,setRef]=useState('main'),[paths,setPaths]=useState('README.md');
 const [jobs,setJobs]=useState<GithubImportJob[]>([]),[job,setJob]=useState<GithubImportJob|null>(null),[busy,setBusy]=useState(false),[text,setText]=useState(''),[name,setName]=useState('GitHub knowledge'),[notice,setNotice]=useState('');
 const [connection,setConnection]=useState<GithubConnectionStatus|null>(null),[privateMode,setPrivateMode]=useState(false);
 useEffect(()=>{setConnection(null);setPrivateMode(false);if(!address)return;let alive=true;void client.githubConnector().then(value=>{if(alive)setConnection(value);});return()=>{alive=false;};},[address,client]);
 const previewEpoch=useRef(0);
 function invalidatePreview(){previewEpoch.current++;setText('');}
 const identity=useRef(address),epoch=useRef(0);if(identity.current!==address){identity.current=address;epoch.current++;}const generation=epoch.current;
 const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);const current=()=>mounted.current&&epoch.current===generation;
 useEffect(()=>{setJob(null);invalidatePreview();setJobs([]);setBusy(false);setNotice('');onInvalidated();if(!address)return;let alive=true;void client.githubImport().then(result=>{if(alive&&result?.jobs){setJobs(result.jobs);setJob(previous=>previous??result.jobs!.find(j=>['queued','running'].includes(j.status))??null);}});return()=>{alive=false;};},[address,client]);
 useEffect(()=>{if(!address||(!busy&&!['queued','running'].includes(job?.status??'')))return;let alive=true;const timer=setInterval(()=>{void client.githubImport().then(result=>{if(alive&&result?.jobs){setJobs(result.jobs);setJob(previous=>previous?result.jobs!.find(j=>j.id===previous.id)??previous:result.jobs!.find(j=>['queued','running'].includes(j.status))??null);}});},2000);return()=>{alive=false;clearInterval(timer);};},[address,client,busy,job?.status]);
 async function start(){if(busy)return;setBusy(true);invalidatePreview();setNotice('Fetching only your selected files.');const result=await client.githubImport('','POST',{...(privateMode&&connection?.id?{connectionId:connection.id}:{}),repository:repository.trim(),ref:ref.trim(),paths:paths.split('\n').map(p=>p.trim()).filter(Boolean)});if(!current())return;setBusy(false);if(result){invalidatePreview();setJob(result);setJobs(previous=>[result,...previous.filter(j=>j.id!==result.id)].slice(0,100));setNotice(result.status==='review_ready'?'Private draft ready. Preview and review before registration.':'Check job status below.');}else setNotice(client.state.error||'Import unavailable. Check owner/repository, ref and 1 to 10 relative Markdown or TXT paths.');}
 async function command(action:'run'|'cancel'){if(!job)return;if(action==='cancel')invalidatePreview();setBusy(true);const result=await client.githubImport(job.id+'/'+action,'POST',{});if(!current())return;setBusy(false);if(result){invalidatePreview();setJob(result);setJobs(previous=>[result,...previous.filter(j=>j.id!==result.id)].slice(0,100));if(action==='cancel'){setText('');onInvalidated();}}else setNotice(client.state.error);}
 async function preview(){if(!job)return;const previewGeneration=++previewEpoch.current;const result=await client.githubDraft(job.id);if(current()&&previewEpoch.current===previewGeneration&&result!==null){setText(result);setName(job.paths[0].split('/').at(-1)!.replace(/\.(md|txt)$/i,''));}else if(current()&&previewEpoch.current===previewGeneration&&result===null)setNotice(client.state.error);}
 async function download(){if(!job)return;const previewGeneration=previewEpoch.current;const result=await client.githubDraft(job.id,true);if(!current()||previewEpoch.current!==previewGeneration)return;if(result===null){setNotice(client.state.error);return;}const url=URL.createObjectURL(new Blob([result],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='github-import.md';a.click();URL.revokeObjectURL(url);}
 if(!address)return <div className="dv-source-text"><p>Sign in with the publishing owner wallet to import selected public GitHub files.</p><button type="button" className="dv-button secondary" disabled={state.loading} onClick={()=>void client.signIn()}>Sign in to import</button><Link to="/settings">Account settings</Link>{state.error&&<p role="alert">{state.error}</p>}</div>;
 return <div className="dv-source-text" style={{minWidth:0,maxWidth:'100%'}}><p>Imports stay private for 24 hours until you review and confirm registration. Private repositories require a read-only GitHub App connected to selected repositories.</p>{connection?.providerConfigured?<><Link to="/settings">Manage GitHub connection</Link>{connection.status==='connected'&&<label><input type="checkbox" checked={privateMode} onChange={e=>{setPrivateMode(e.target.checked);setRepository('');invalidatePreview();onInvalidated();}}/> Use my connected private GitHub repositories</label>}</>:<p>Private GitHub is unavailable until the provider is configured. <Link to="/settings">Connection settings</Link></p>}
 {privateMode?<label>Selected repository<select value={repository} onChange={e=>setRepository(e.target.value)}><option value="">Choose a selected repository</option>{connection?.repositories.map(r=><option key={r.id} value={r.name}>{r.name}</option>)}</select></label>:<label>Public repository<input value={repository} maxLength={140} placeholder="owner/repository" onChange={e=>setRepository(e.target.value)}/></label>}<label>Branch or exact commit<input value={ref} maxLength={100} onChange={e=>setRef(e.target.value)}/></label><label>Selected Markdown or TXT paths, one per line<textarea value={paths} maxLength={2500} rows={3} onChange={e=>setPaths(e.target.value)}/></label>
 <button type="button" className="dv-button secondary" disabled={busy||!repository.trim()||!ref.trim()||!paths.trim()} onClick={()=>void start()}>{busy?'Import in progress':'Import selected files'}</button><p role="status">{notice}</p>
 {jobs.length>0&&<label>Recover an import<select value={job?.id??''} onChange={e=>{invalidatePreview();setJob(jobs.find(j=>j.id===e.target.value)??null);onInvalidated();}}><option value="">Choose a private import</option>{jobs.map(j=><option key={j.id} value={j.id}>{j.repository} ({j.status})</option>)}</select></label>}
 {job&&<section aria-label="GitHub import status"><p>Status: {job.status}</p><p style={{overflowWrap:'anywhere'}}>Repository: {job.repository}<br/>Exact commit: {job.commitSha??'Resolving'}<br/>Selected paths: {job.paths.join(', ')}<br/>Draft expires: {new Date(job.expiresAt).toLocaleString()}</p>{job.error&&<p role="alert">{job.error}</p>}
 {['queued','running','failed'].includes(job.status)&&<button type="button" className="dv-button secondary" disabled={busy||job.attempts>=3} onClick={()=>void command('run')}>Retry or resume import</button>}
 {!['cancelled','expired'].includes(job.status)&&<button type="button" className="dv-button secondary" onClick={()=>void command('cancel')}>Cancel import</button>}
 {job.status==='review_ready'&&<><button type="button" className="dv-button secondary" onClick={()=>void preview()}>Preview private draft</button><button type="button" className="dv-button secondary" onClick={()=>void download()}>Download private draft</button></>}
 {text&&job.status==='review_ready'&&<><label>Collection name<input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><label>Review and edit imported text<textarea value={text} rows={8} maxLength={500000} onChange={e=>setText(e.target.value)}/></label><p>Review the source and name, then set your price and accept the disclosure in the registration form. Wallet signing and on-chain confirmation publish a new immutable collection. Failed registration leaves this draft recoverable.</p><button type="button" className="dv-button" disabled={!name.trim()||!text.trim()||new TextEncoder().encode(text).byteLength>500000} onClick={()=>onReviewed(name,text)}>Use reviewed draft in registration</button></>}
 </section>}</div>;
}
