import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router';
import {useAccount} from './account';
import {useWorkspace} from './data';
import type {TeamWorkspace,TeamInvitation,TeamMember,TeamCollection,TeamRole} from './account-client';
const roles:TeamRole[]=['Owner','Editor','Viewer'];
export default function TeamSettings(){
 const {client,state}=useAccount(),owned=useWorkspace();
 const identity=state.session?state.session.account.address+':'+state.session.csrfToken:'';
 const current=useRef(identity);current.current=identity;
 const mounted=useRef(true);
 const [loadedFor,setLoadedFor]=useState(''),[teams,setTeams]=useState<TeamWorkspace[]>([]),[received,setReceived]=useState<TeamInvitation[]>([]);
 const [selected,setSelected]=useState<TeamWorkspace|null>(null),[members,setMembers]=useState<TeamMember[]>([]),[invitations,setInvitations]=useState<TeamInvitation[]>([]),[collections,setCollections]=useState<TeamCollection[]>([]),[cursor,setCursor]=useState<string|null>(null);
 const [newName,setNewName]=useState(''),[settingsName,setSettingsName]=useState(''),[wallet,setWallet]=useState(''),[role,setRole]=useState<TeamRole>('Viewer'),[collectionId,setCollectionId]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [edit,setEdit]=useState<TeamCollection|null>(null),[confirmation,setConfirmation]=useState<{path:string;label:string}|null>(null);
 const selection=useRef<string|null>(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const valid=(captured:string)=>mounted.current&&current.current===captured;
 async function refresh(captured=identity){const result=await client.teams();if(valid(captured)){if(result){setTeams(result.workspaces);setReceived(result.invitations);setLoadedFor(captured);}else setError(client.state.error||'Team access unavailable. Retry.');}}
 useEffect(()=>{selection.current=null;setLoadedFor('');setTeams([]);setReceived([]);setSelected(null);setMembers([]);setInvitations([]);setCollections([]);setCursor(null);setEdit(null);setConfirmation(null);setWallet('');setNewName('');setCollectionId('');setBusy(false);setError('');setNotice('');if(identity)void refresh(identity);},[identity]);
 async function load(id:string,captured=identity){
  selection.current=id;setSelected(null);setCollections([]);setMembers([]);setInvitations([]);setEdit(null);setConfirmation(null);setCursor(null);setError('');setBusy(true);
  try {const detail=await client.workspaceRequest<{workspace:TeamWorkspace}>(id);if(!valid(captured)||selection.current!==id)return;if(!detail){setError(client.state.error||'Workspace unavailable.');return;}
   const m=await client.workspaceRequest<{members:TeamMember[]}>(id+'/members?limit=50');const c=await client.workspaceRequest<{collections:TeamCollection[];nextCursor:string|null}>(id+'/collections?limit=50');const i=detail.workspace.role==='Owner'?await client.workspaceRequest<{invitations:TeamInvitation[]}>(id+'/invitations?limit=50'):null;
   if(!valid(captured)||selection.current!==id)return;if(!m||!c||(detail.workspace.role==='Owner'&&!i)){setError(client.state.error||'Workspace data unavailable. Retry.');return;}
   setSelected(detail.workspace);setSettingsName(detail.workspace.name);setMembers(m.members);setCollections(c.collections);setCursor(c.nextCursor);setInvitations(i?.invitations??[]);
  }finally{if(valid(captured)&&selection.current===id)setBusy(false);}
 }
 async function mutation(path:string,method:string,input:unknown={},message='Workspace updated.'){
  const captured=identity,id=selected?.id;setBusy(true);setError('');setNotice('');
  try {const result=await client.workspaceRequest(path,method,input);if(!valid(captured))return;if(!result){setError(client.state.error||'Operation rejected. Keep at least one Owner, check limits and current access, then refresh.');return;}setNotice(message);setConfirmation(null);await refresh(captured);if(id&&!path.endsWith('/leave'))await load(id,captured);else{selection.current=null;setSelected(null);setCollections([]);setMembers([]);}}
  finally{if(valid(captured))setBusy(false);}
 }
 async function create(){const captured=identity;setBusy(true);setError('');const result=await client.createWorkspace(newName);if(valid(captured)){if(result){setNewName('');await refresh(captured);await load(result.workspace.id,captured);}else setError(client.state.error||'Creation rejected. Maximum 5 owned workspaces.');setBusy(false);}}
 async function saveMetadata(){if(!selected||!edit)return;const captured=identity,id=selected.id;setBusy(true);const result=await client.teamMetadata(id,edit.collectionId,{description:edit.description,category:edit.category,visibility:edit.visibility});if(valid(captured)){if(result){setNotice('Shared metadata saved.');await load(id,captured);}else setError(client.state.error||'Metadata update rejected. Refresh current permissions.');setBusy(false);}}
 async function more(){if(!selected||!cursor)return;const captured=identity,id=selected.id;setBusy(true);const page=await client.workspaceRequest<{collections:TeamCollection[];nextCursor:string|null}>(id+'/collections?limit=50&cursor='+encodeURIComponent(cursor));if(valid(captured)&&selection.current===id){if(page){setCollections(old=>[...old,...page.collections]);setCursor(page.nextCursor);}else setError(client.state.error||'Shared collections unavailable.');setBusy(false);}}
 if(!identity)return <section className="dv-team-settings"><h3>Team workspaces</h3><p>Sign in to manage wallet invitations and shared collection metadata.</p></section>;
 const visible=loadedFor===identity,team=visible?selected:null;
 return <section className="dv-team-settings"><h3>Team workspaces</h3><p>Owners manage members, settings and sharing. Editors edit explicitly shared metadata. Viewers read it. Payments, prices, publishing, pause controls, source content and paid answers stay with the original wallet owner.</p>
 {(error||state.error)&&<p role="alert">{error||state.error}</p>}{notice&&<p role="status">{notice}</p>}
 <button className="dv-button secondary" disabled={busy||state.loading} onClick={()=>void refresh()}>Refresh workspaces and invitations</button>
 {!visible?<p>Loading team access. Retry refresh if it does not load.</p>:<>
 <form onSubmit={e=>{e.preventDefault();void create();}}><label>New workspace name<input className="dv-input" required maxLength={80} value={newName} onChange={e=>setNewName(e.target.value)} disabled={busy}/></label><p>Maximum 5 owned workspaces per wallet and deployment.</p><button className="dv-button" disabled={busy||state.loading||!newName.trim()}>Create workspace</button></form>
 <h4>Your invitations</h4>{received.length?received.map(i=><article key={i.id}><p>{i.name}: {i.role}. Expires {new Date(i.expiresAt).toLocaleString()}.</p><button className="dv-button secondary" disabled={busy||state.loading} onClick={()=>void mutation(i.workspaceId+'/invitations/'+i.id+'/accept','POST',{},'Invitation accepted.')}>Accept invitation</button></article>):<p>No pending invitations for this wallet.</p>}
 <h4>Your workspaces</h4>{teams.length?teams.map(w=><button className="dv-button secondary" key={w.id} disabled={busy||state.loading} onClick={()=>void load(w.id)}>{w.name} ({w.role})</button>):<p>No workspaces yet.</p>}
 {busy&&<p role="status">Loading or saving workspace...</p>}
 {team&&<><h4>{team.name}</h4><p>Your role: {team.role}. {team.role==='Owner'?'Manage members, settings and collection sharing.':team.role==='Editor'?'Edit explicitly shared off-chain metadata.':'Read explicitly shared metadata.'}</p>
 {team.role==='Owner'&&<><form onSubmit={e=>{e.preventDefault();void mutation(team.id,'PATCH',{name:settingsName});}}><label>Workspace name<input className="dv-input" maxLength={80} value={settingsName} onChange={e=>setSettingsName(e.target.value)} required disabled={busy}/></label><button className="dv-button secondary" disabled={busy||state.loading}>Save workspace name</button></form>
 <form onSubmit={e=>{e.preventDefault();void mutation(team.id+'/invitations','POST',{address:wallet,role},'Wallet invitation created. Share acceptance instructions yourself; no message was sent.');}}><label>Invite wallet<input className="dv-input" placeholder="0x..." pattern="0x[a-fA-F0-9]{40}" value={wallet} onChange={e=>setWallet(e.target.value)} required disabled={busy}/></label><label>Invitation role<select className="dv-input" value={role} onChange={e=>setRole(e.target.value as TeamRole)} disabled={busy}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><p>Invitations expire after 7 days. Maximum 50 members and 50 pending invitations. The invited wallet signs into its own account to accept.</p><button className="dv-button secondary" disabled={busy||state.loading}>Create wallet invitation</button></form>
 {invitations.map(i=><article key={i.id}><p className="dv-account-address">{i.address}</p><p>{i.role}, expires {new Date(i.expiresAt).toLocaleString()}</p><button className="dv-button secondary" disabled={busy||state.loading} onClick={()=>void mutation(team.id+'/invitations/'+i.id,'DELETE')}>Revoke invitation</button></article>)}
 </>}
 <h4>Members</h4>{members.map(m=><article className="dv-team-member" key={m.address}><p className="dv-account-address">{m.address}</p>{team.role==='Owner'?<><label>Role<select className="dv-input" value={m.role} disabled={busy||state.loading} onChange={e=>void mutation(team.id+'/members/'+m.address,'PATCH',{role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><button className="dv-button secondary" disabled={busy||state.loading} onClick={()=>setConfirmation({path:team.id+'/members/'+m.address,label:'Remove this wallet from the workspace?'})}>Remove member</button></>:<p>{m.role}</p>}</article>)}
 <p>The last Owner must appoint another Owner before leaving or removing their Owner role. A pending account deletion request does not transfer these responsibilities.</p><button className="dv-button secondary" disabled={busy||state.loading} onClick={()=>setConfirmation({path:team.id+'/leave',label:'Leave this workspace and end your shared access?'})}>Leave workspace</button>
 {confirmation&&<div><p>{confirmation.label}</p><button className="dv-button secondary" disabled={busy||state.loading} onClick={()=>void mutation(confirmation.path,confirmation.path.endsWith('/leave')?'POST':'DELETE')}>Confirm</button><button className="dv-button secondary" disabled={busy} onClick={()=>setConfirmation(null)}>Cancel</button></div>}
 <h4>Shared collection metadata</h4>{team.role==='Owner'&&<><button className="dv-button secondary" disabled={busy||owned.loading} onClick={()=>void owned.load('collections')}>Load my wallet-owned collections</button>{owned.collections.error&&<p role="alert">{owned.collections.error}</p>}<form onSubmit={e=>{e.preventDefault();void mutation(team.id+'/collections','POST',{collectionId});}}><label>Collection to share<select className="dv-input" required value={collectionId} disabled={busy} onChange={e=>setCollectionId(e.target.value)}><option value="">Select a wallet-owned collection</option>{(owned.collections.data?.collections??[]).map(c=><option key={c.collectionId} value={c.collectionId}>{c.name}</option>)}</select></label><p>Sharing requires current on-chain ownership. A grant stops working when its grantor loses ownership or their workspace Owner role.</p><button className="dv-button secondary" disabled={busy||state.loading||!collectionId}>Share metadata</button></form></>}
 {collections.length?collections.map(c=><article key={c.collectionId}><h4>{c.name}</h4><p>{c.description||'No description.'}</p><p>{c.category}, {c.visibility}</p>{team.role!=='Viewer'&&<button className="dv-button secondary" disabled={busy} onClick={()=>setEdit({...c})}>Edit shared metadata</button>}{team.role==='Owner'&&<button className="dv-button secondary" disabled={busy} onClick={()=>void mutation(team.id+'/collections/'+c.collectionId,'DELETE')}>Remove metadata sharing</button>}</article>):<p>No currently valid shared collections.</p>}
 {cursor&&<button className="dv-button secondary" disabled={busy} onClick={()=>void more()}>Load more shared collections</button>}
 {edit&&<form onSubmit={e=>{e.preventDefault();void saveMetadata();}}><h4>Edit {edit.name}</h4><label>Description<textarea className="dv-input" maxLength={2000} value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})} disabled={busy}/></label><label>Category<select className="dv-input" value={edit.category} onChange={e=>setEdit({...edit,category:e.target.value})} disabled={busy}>{['General','Technology','Business','Research','Education','Finance','Legal','Other'].map(c=><option key={c}>{c}</option>)}</select></label><label>Visibility<select className="dv-input" value={edit.visibility} onChange={e=>setEdit({...edit,visibility:e.target.value})} disabled={busy}><option value="public">Public</option><option value="unlisted">Unlisted</option></select></label><button className="dv-button" disabled={busy||state.loading}>Save metadata</button><button type="button" className="dv-button secondary" disabled={busy} onClick={()=>setEdit(null)}>Cancel edit</button></form>}
 <p>On-chain changes require the collection owner's wallet. Team access never grants payout or paid-query authority.</p><Link className="dv-button secondary" to="/collections">Wallet owner collection controls</Link><Link className="dv-button secondary" to="/api-access">Developer keys</Link>
 </>}
 </>}
 </section>;
}
